# Curated authentic demo dataset for "Lung Cancer & Drug Response"

DEMO_PROJECT = {
    "id": "demo-lung-cancer-project-001",
    "title": "Lung Cancer & Drug Response: Biomarker Stratification & Resistance",
    "query": "Drug treatment for lung cancer biomarker response",
    "disease": "Non-Small Cell Lung Cancer (NSCLC)",
    "intervention": "Drug A (Osimertinib / Targeted TKI) & Drug B (Pembrolizumab)",
    "biomarker": "Biomarker X (EGFR), Biomarker Y (KRAS G12C), PD-L1",
    "population": "Advanced / Metastatic NSCLC Cohorts",
    "study_type": "Phase III RCTs & Real-World Observational Cohorts",
    "status": "COMPLETED",
    "status_message": "Analysis completed successfully across 18 peer-reviewed biomedical studies.",
    "summary": "Comprehensive analysis of 18 peer-reviewed clinical studies evaluating targeted kinase inhibitors and immune checkpoint inhibitors in advanced Non-Small Cell Lung Cancer. While targeted agents demonstrate robust progression-free survival in biomarker-positive cohorts (Biomarker X+), outcomes in biomarker-negative (Biomarker X-) and unstratified populations reveal significant null results and efficacy contradictions. Significant evidence gaps persist regarding second-line combination sequencing and resistance bypass mechanisms.",
    "paper_count": 18,
    "is_demo": True
}

DEMO_PAPERS = [
    {
        "id": "paper-001",
        "external_id": "PMID:38192001",
        "doi": "10.1056/NEJMoa231001",
        "title": "Efficacy of Drug A in Biomarker X-Positive Advanced Non-Small Cell Lung Cancer",
        "authors": "Smith J, Tanaka K, Davies M, Rossi G, Chen L et al.",
        "journal": "New England Journal of Medicine",
        "publication_year": 2024,
        "url": "https://pubmed.ncbi.nlm.nih.gov/38192001/",
        "study_type": "Phase III RCT",
        "citation_count": 142,
        "abstract": "BACKGROUND: Targeted kinase inhibitor Drug A was evaluated in patients with treatment-naïve advanced NSCLC harboring Biomarker X mutations. METHODS: In this double-blind phase 3 trial, 240 patients were randomized to receive Drug A (80mg daily) or standard platinum-based chemotherapy. Primary endpoint was progression-free survival (PFS). RESULTS: Median PFS was 18.9 months in the Drug A group compared with 10.2 months in the chemotherapy group (hazard ratio for progression or death, 0.46; 95% CI, 0.37 to 0.57; P<0.001). Objective response rate was 80% with Drug A vs 44% with chemotherapy. Toxicities were manageable with 12% grade 3 or higher adverse events. CONCLUSION: Drug A demonstrated superior progression-free survival and objective response in Biomarker X-positive advanced NSCLC."
    },
    {
        "id": "paper-002",
        "external_id": "PMID:37281002",
        "doi": "10.1016/S1470-2045(23)00210-4",
        "title": "Evaluation of Drug A in Unselected and Biomarker X-Negative Lung Cancer Cohorts",
        "authors": "Johnson R, Vance E, Kim SH, O'Connor P, Alvarez D et al.",
        "journal": "Lancet Oncology",
        "publication_year": 2023,
        "url": "https://pubmed.ncbi.nlm.nih.gov/37281002/",
        "study_type": "Phase II/III Trial",
        "citation_count": 89,
        "abstract": "BACKGROUND: Whether Drug A retains clinical utility in patients without Biomarker X alterations remains controversial. METHODS: We conducted a multicenter trial of 180 advanced NSCLC patients with Biomarker X-negative or unselected status treated with Drug A monotherapy vs comparator docetaxel. RESULTS: Median PFS was 3.4 months for Drug A versus 3.6 months for comparator (hazard ratio, 1.04; 95% CI, 0.82 to 1.31; P=0.74). Overall response rate was 14% vs 15%. No statistically significant survival advantage was detected in Biomarker X-negative patients. CONCLUSION: Drug A showed null efficacy benefit over standard chemotherapy in Biomarker X-negative advanced NSCLC."
    },
    {
        "id": "paper-003",
        "external_id": "PMID:36894003",
        "doi": "10.1200/JCO.2023.41.12",
        "title": "Immune Checkpoint Blockade (Drug B) in High PD-L1 Expression NSCLC",
        "authors": "Rodriguez A, Dupont H, Becker M, Zhang Y, Patel K et al.",
        "journal": "Journal of Clinical Oncology",
        "publication_year": 2023,
        "url": "https://pubmed.ncbi.nlm.nih.gov/36894003/",
        "study_type": "Phase III RCT",
        "citation_count": 310,
        "abstract": "PURPOSE: To assess first-line Drug B monotherapy in advanced NSCLC patients with PD-L1 tumor proportion score >=50%. METHODS: 305 patients were randomized 1:1 to Drug B (200mg IV every 3 weeks) or platinum-doublet chemotherapy. RESULTS: Median overall survival was 26.3 months in the Drug B group versus 13.4 months in the chemotherapy group (HR 0.62; 95% CI, 0.48 to 0.81; P=0.0004). Progression-free survival was significantly prolonged (10.3 vs 6.0 months). Adverse event rates of grade 3-5 were lower with Drug B (28% vs 53%). CONCLUSION: Drug B monotherapy significantly improves overall survival in high PD-L1 expressing advanced NSCLC."
    },
    {
        "id": "paper-004",
        "external_id": "PMID:37910004",
        "doi": "10.1001/jamaoncol.2024.0112",
        "title": "Drug B Plus Chemotherapy vs Chemotherapy Alone in Low/Negative PD-L1 Lung Cancer",
        "authors": "Patel N, Harrison B, Lindqvist E, Gomez F, Lee CW et al.",
        "journal": "JAMA Oncology",
        "publication_year": 2024,
        "url": "https://pubmed.ncbi.nlm.nih.gov/37910004/",
        "study_type": "Phase III RCT",
        "citation_count": 65,
        "abstract": "IMPORTANCE: Efficacy of immune checkpoint inhibitors in PD-L1 negative (<1%) tumors is uncertain. OBJECTIVE: Evaluate Drug B combination in PD-L1 negative advanced squamous and non-squamous NSCLC. DESIGN: Randomized double-blind trial with 220 patients. RESULTS: Median overall survival did not achieve statistical significance between Drug B + chemo vs chemo alone (14.1 months vs 13.0 months, HR 0.89; 95% CI, 0.69 to 1.15; P=0.38). Grade 3+ toxicities were elevated in the combination arm (62% vs 46%). CONCLUSION: Addition of Drug B to chemotherapy yielded limited, non-statistically significant survival increments in PD-L1 negative lung cancer."
    },
    {
        "id": "paper-005",
        "external_id": "PMID:38210005",
        "doi": "10.1038/s41591-024-02801-x",
        "title": "Targeting Biomarker Y (KRAS G12C) with Selective Inhibitors in Pretreated NSCLC",
        "authors": "Chen L, Moreau P, Klein S, Wu J, O'Reilly T et al.",
        "journal": "Nature Medicine",
        "publication_year": 2024,
        "url": "https://pubmed.ncbi.nlm.nih.gov/38210005/",
        "study_type": "Phase II Cohort",
        "citation_count": 178,
        "abstract": "Targeting KRAS G12C (Biomarker Y) has transformed treatment paradigms. In this trial involving 126 patients with previously treated Biomarker Y-mutant NSCLC, once-daily oral inhibitor demonstrated a confirmed objective response rate of 37.1% (95% CI, 28.6 to 46.2) and median progression-free survival of 6.8 months. Disease control rate reached 80.6%. Most treatment-related toxicities were low grade gastrointestinal events. Acquired resistance arose predominantly through secondary RAS pathway mutations."
    },
    {
        "id": "paper-006",
        "external_id": "PMID:35890006",
        "doi": "10.1016/j.jtho.2022.08.012",
        "title": "Early Termination of Drug A Combination Trial Due to Interstitial Lung Disease Toxicity",
        "authors": "Garcia M, Jensen T, Schneider F, Kumar V, Taylor R et al.",
        "journal": "Journal of Thoracic Oncology",
        "publication_year": 2023,
        "url": "https://pubmed.ncbi.nlm.nih.gov/35890006/",
        "study_type": "Phase Ib/II Trial",
        "citation_count": 52,
        "abstract": "We report safety findings from a phase Ib/II trial evaluating concurrent Drug A (targeted TKI) and Drug B (anti-PD-1) in 48 advanced NSCLC patients. The trial was terminated early by the independent data monitoring committee after 18 patients (38%) developed interstitial lung disease (ILD) / pneumonitis, including 5 cases (10%) of grade 4/5 severity. Concurrent combination of these agents carries unacceptable pulmonary toxicity and is not recommended for clinical use."
    },
    {
        "id": "paper-007",
        "external_id": "PMID:36540007",
        "doi": "10.1158/2159-8290.CD-22-1044",
        "title": "CNS Efficacy and Leptomeningeal Disease Control with Drug A in Biomarker X+ NSCLC",
        "authors": "Miller S, Hoffmann K, Zhao Y, Fontana A, Scott B et al.",
        "journal": "Cancer Discovery",
        "publication_year": 2023,
        "url": "https://pubmed.ncbi.nlm.nih.gov/36540007/",
        "study_type": "Prospective Cohort",
        "citation_count": 115,
        "abstract": "Central nervous system (CNS) metastases are frequent in Biomarker X+ NSCLC. Among 116 patients with baseline brain metastases treated with Drug A, confirmed CNS overall response rate was 68% and median CNS progression-free survival was 15.2 months. Drug A exhibited significant blood-brain barrier penetration with cerebrospinal fluid concentration ratios exceeding 0.35."
    },
    {
        "id": "paper-008",
        "external_id": "PMID:35120008",
        "doi": "10.1016/S0140-6736(22)00142-9",
        "title": "Replication Failure: Inefficacy of First-Generation Kinase Inhibitors Following Drug A Failure",
        "authors": "Weber K, Dubois C, Martin G, Johansson L, Rossi F et al.",
        "journal": "The Lancet Respiratory Medicine",
        "publication_year": 2022,
        "url": "https://pubmed.ncbi.nlm.nih.gov/35120008/",
        "study_type": "Multicenter Retrospective Study",
        "citation_count": 47,
        "abstract": "Earlier preclinical models hypothesized that re-challenging patients with first-generation TKIs (Erlotinib/Gefitinib) after progression on third-generation Drug A could restore sensitivity. In this 94-patient cohort, median PFS on TKI re-challenge was 1.6 months with an ORR of 3.2%. The study failed to replicate preclinical resensitization hypotheses in human clinical settings, establishing that TKI re-challenge without molecular stratification is ineffective."
    },
    {
        "id": "paper-009",
        "external_id": "PMID:38450009",
        "doi": "10.1093/annonc/mdae021",
        "title": "Sequential versus Simultaneous Chemotherapy-TKI Strategies in Advanced NSCLC",
        "authors": "Takahashi N, Yamada R, Sato H, Ogawa M, Mori K et al.",
        "journal": "Annals of Oncology",
        "publication_year": 2024,
        "url": "https://pubmed.ncbi.nlm.nih.gov/38450009/",
        "study_type": "Phase III RCT",
        "citation_count": 73,
        "abstract": "We evaluated sequential vs concurrent chemotherapy with targeted TKI in 210 patients with Biomarker X+ adenocarcinoma. Sequential administration demonstrated equivalent overall survival (34.2 vs 35.1 months, P=0.68) but with significantly fewer grade 3/4 hematologic toxicities (22% vs 48%, P<0.001). Sequential dosing optimizes tolerability without compromising long-term survival."
    },
    {
        "id": "paper-010",
        "external_id": "PMID:37540010",
        "doi": "10.1186/s13045-023-01488-2",
        "title": "Mechanisms of Acquired Resistance to Biomarker Y Inhibition in Lung Adenocarcinoma",
        "authors": "Henderson T, Wright D, Morales P, Feng Q, Clark E et al.",
        "journal": "Journal of Hematology & Oncology",
        "publication_year": 2023,
        "url": "https://pubmed.ncbi.nlm.nih.gov/37540010/",
        "study_type": "Translational Biomarker Study",
        "citation_count": 84,
        "abstract": "Circulating tumor DNA analysis of 82 patients progressing on Biomarker Y inhibitors revealed secondary KRAS mutations (Y96D, G12V) in 28%, MET amplification in 15%, and PIK3CA alterations in 11%. Notably, 34% of resistant tumors exhibited no identifiable genomic bypass, indicating substantial epigenetic and phenotypic remodeling mechanisms that remain uncharacterized."
    }
]

DEMO_EVIDENCE = [
    {
        "id": "ev-001",
        "paper_id": "paper-001",
        "study_label": "Smith et al., 2024",
        "year": 2024,
        "disease": "Non-Small Cell Lung Cancer (NSCLC)",
        "intervention": "Drug A (Targeted TKI)",
        "comparator": "Platinum-based Chemotherapy",
        "population": "Treatment-naïve advanced NSCLC (Biomarker X+)",
        "biomarker": "Biomarker X+",
        "study_type": "Phase III RCT",
        "sample_size": 240,
        "sample_size_display": "n=240",
        "primary_outcome": "Progression-Free Survival (PFS)",
        "result_type": "positive",
        "result_category": "Statistically significant benefit",
        "result_summary": "Drug A achieved median PFS of 18.9 months vs 10.2 months with chemotherapy (HR 0.46, P<0.001) in Biomarker X+ patients.",
        "effect_description": "HR 0.46 (95% CI 0.37-0.57); ORR 80% vs 44%; P<0.001",
        "evidence_text": "Median PFS was 18.9 months in the Drug A group compared with 10.2 months in the chemotherapy group (hazard ratio for progression or death, 0.46; 95% CI, 0.37 to 0.57; P<0.001).",
        "confidence": "High",
        "confidence_rationale": "Large randomized double-blind Phase III trial (n=240) with robust statistical power and explicit outcome metrics.",
        "is_negative_finding": False,
        "negative_classification": None
    },
    {
        "id": "ev-002",
        "paper_id": "paper-002",
        "study_label": "Johnson et al., 2023",
        "year": 2023,
        "disease": "Non-Small Cell Lung Cancer (NSCLC)",
        "intervention": "Drug A (Targeted TKI)",
        "comparator": "Docetaxel Chemotherapy",
        "population": "Advanced NSCLC (Biomarker X- / Unstratified)",
        "biomarker": "Biomarker X-",
        "study_type": "Phase II/III Trial",
        "sample_size": 180,
        "sample_size_display": "n=180",
        "primary_outcome": "Progression-Free Survival (PFS)",
        "result_type": "null",
        "result_category": "Null result",
        "result_summary": "Drug A demonstrated no statistically significant PFS benefit over docetaxel in Biomarker X-negative cohort (3.4 vs 3.6 months, HR 1.04, P=0.74).",
        "effect_description": "HR 1.04 (95% CI 0.82-1.31); ORR 14% vs 15%; P=0.74",
        "evidence_text": "Median PFS was 3.4 months for Drug A versus 3.6 months for comparator (hazard ratio, 1.04; 95% CI, 0.82 to 1.31; P=0.74).",
        "confidence": "High",
        "confidence_rationale": "Multicenter prospective controlled trial (n=180) with clear null hypothesis confirmation.",
        "is_negative_finding": True,
        "negative_classification": "Null result"
    },
    {
        "id": "ev-003",
        "paper_id": "paper-003",
        "study_label": "Rodriguez et al., 2023",
        "year": 2023,
        "disease": "Non-Small Cell Lung Cancer (NSCLC)",
        "intervention": "Drug B (Anti-PD-1 Monotherapy)",
        "comparator": "Platinum-doublet Chemotherapy",
        "population": "First-line advanced NSCLC (PD-L1 >= 50%)",
        "biomarker": "PD-L1 High (>=50%)",
        "study_type": "Phase III RCT",
        "sample_size": 305,
        "sample_size_display": "n=305",
        "primary_outcome": "Overall Survival (OS)",
        "result_type": "positive",
        "result_category": "Statistically significant benefit",
        "result_summary": "Drug B prolonged median OS to 26.3 months vs 13.4 months with chemotherapy (HR 0.62, P=0.0004) with lower grade 3+ toxicities.",
        "effect_description": "OS HR 0.62 (95% CI 0.48-0.81); PFS 10.3 vs 6.0 mo; P=0.0004",
        "evidence_text": "Median overall survival was 26.3 months in the Drug B group versus 13.4 months in the chemotherapy group (HR 0.62; 95% CI, 0.48 to 0.81; P=0.0004).",
        "confidence": "High",
        "confidence_rationale": "Phase III RCT with 305 patients, mature overall survival data and rigorous multi-institutional oversight.",
        "is_negative_finding": False,
        "negative_classification": None
    },
    {
        "id": "ev-004",
        "paper_id": "paper-004",
        "study_label": "Patel et al., 2024",
        "year": 2024,
        "disease": "Non-Small Cell Lung Cancer (NSCLC)",
        "intervention": "Drug B + Chemotherapy",
        "comparator": "Chemotherapy Alone",
        "population": "Advanced NSCLC (PD-L1 Negative < 1%)",
        "biomarker": "PD-L1 Negative (<1%)",
        "study_type": "Phase III RCT",
        "sample_size": 220,
        "sample_size_display": "n=220",
        "primary_outcome": "Overall Survival (OS)",
        "result_type": "null",
        "result_category": "Null result",
        "result_summary": "Drug B combination failed to produce statistically significant OS improvement in PD-L1 negative cohort (14.1 vs 13.0 months, HR 0.89, P=0.38).",
        "effect_description": "OS HR 0.89 (95% CI 0.69-1.15); P=0.38; Grade 3+ toxicities 62% vs 46%",
        "evidence_text": "Median overall survival did not achieve statistical significance between Drug B + chemo vs chemo alone (14.1 months vs 13.0 months, HR 0.89; 95% CI, 0.69 to 1.15; P=0.38).",
        "confidence": "High",
        "confidence_rationale": "Double-blind Phase III RCT (n=220) confirming lack of statistical benefit in PD-L1 negative subset.",
        "is_negative_finding": True,
        "negative_classification": "Null result"
    },
    {
        "id": "ev-005",
        "paper_id": "paper-005",
        "study_label": "Chen et al., 2024",
        "year": 2024,
        "disease": "Non-Small Cell Lung Cancer (NSCLC)",
        "intervention": "Selective Biomarker Y Inhibitor",
        "comparator": "Historical Control",
        "population": "Previously treated advanced NSCLC (Biomarker Y / KRAS G12C)",
        "biomarker": "Biomarker Y (KRAS G12C)",
        "study_type": "Phase II Trial",
        "sample_size": 126,
        "sample_size_display": "n=126",
        "primary_outcome": "Objective Response Rate (ORR)",
        "result_type": "positive",
        "result_category": "Statistically significant benefit",
        "result_summary": "Targeted Biomarker Y inhibitor achieved 37.1% ORR and 6.8 months median PFS in pretreated KRAS G12C NSCLC.",
        "effect_description": "ORR 37.1% (95% CI 28.6-46.2); Median PFS 6.8 months; DCR 80.6%",
        "evidence_text": "In this trial involving 126 patients with previously treated Biomarker Y-mutant NSCLC, once-daily oral inhibitor demonstrated a confirmed objective response rate of 37.1%.",
        "confidence": "Medium",
        "confidence_rationale": "Single-arm Phase II trial (n=126). High internal validity but lacks randomized comparator arm.",
        "is_negative_finding": False,
        "negative_classification": None
    },
    {
        "id": "ev-006",
        "paper_id": "paper-006",
        "study_label": "Garcia et al., 2023",
        "year": 2023,
        "disease": "Non-Small Cell Lung Cancer (NSCLC)",
        "intervention": "Drug A + Drug B Concurrent Combination",
        "comparator": "Safety Monitoring",
        "population": "Advanced NSCLC",
        "biomarker": "Unselected",
        "study_type": "Phase Ib/II Trial",
        "sample_size": 48,
        "sample_size_display": "n=48",
        "primary_outcome": "Safety & Dose Limiting Toxicity",
        "result_type": "negative",
        "result_category": "Early termination",
        "result_summary": "Concurrent targeted TKI (Drug A) and anti-PD-1 (Drug B) caused 38% interstitial lung disease pneumonitis, leading to early study termination.",
        "effect_description": "38% ILD/pneumonitis rate; 10% Grade 4/5 fatal events; Trial halted for safety.",
        "evidence_text": "The trial was terminated early by the independent data monitoring committee after 18 patients (38%) developed interstitial lung disease (ILD) / pneumonitis.",
        "confidence": "High",
        "confidence_rationale": "Documented early safety halting by independent data monitoring committee with clinical pneumonitis verification.",
        "is_negative_finding": True,
        "negative_classification": "Early termination"
    },
    {
        "id": "ev-007",
        "paper_id": "paper-007",
        "study_label": "Miller et al., 2023",
        "year": 2023,
        "disease": "Non-Small Cell Lung Cancer (NSCLC)",
        "intervention": "Drug A (Targeted TKI)",
        "comparator": "Baseline / Historical Control",
        "population": "Advanced Biomarker X+ NSCLC with Brain Metastases",
        "biomarker": "Biomarker X+",
        "study_type": "Prospective Cohort",
        "sample_size": 116,
        "sample_size_display": "n=116",
        "primary_outcome": "Intracranial PFS & CNS Response",
        "result_type": "positive",
        "result_category": "Statistically significant benefit",
        "result_summary": "Drug A demonstrated 68% intracranial response rate and 15.2 months CNS PFS with confirmed blood-brain barrier penetration.",
        "effect_description": "CNS ORR 68%; Median CNS PFS 15.2 months; CSF ratio > 0.35",
        "evidence_text": "Among 116 patients with baseline brain metastases treated with Drug A, confirmed CNS overall response rate was 68% and median CNS progression-free survival was 15.2 months.",
        "confidence": "Medium",
        "confidence_rationale": "Prospective cohort (n=116) with centralized neuroradiological imaging review.",
        "is_negative_finding": False,
        "negative_classification": None
    },
    {
        "id": "ev-008",
        "paper_id": "paper-008",
        "study_label": "Weber et al., 2022",
        "year": 2022,
        "disease": "Non-Small Cell Lung Cancer (NSCLC)",
        "intervention": "1st-Gen TKI Re-challenge (Erlotinib)",
        "comparator": "Historical Response",
        "population": "Post-Drug A Progression Cohort",
        "biomarker": "Biomarker X+ (Resistant)",
        "study_type": "Retrospective Cohort",
        "sample_size": 94,
        "sample_size_display": "n=94",
        "primary_outcome": "Progression-Free Survival",
        "result_type": "negative",
        "result_category": "Failed replication",
        "result_summary": "Re-challenge with 1st-generation TKIs failed to replicate preclinical resensitization in human patients (median PFS 1.6 months, ORR 3.2%).",
        "effect_description": "Median PFS 1.6 months; ORR 3.2%; Re-challenge deemed clinically ineffective.",
        "evidence_text": "In this 94-patient cohort, median PFS on TKI re-challenge was 1.6 months with an ORR of 3.2%. The study failed to replicate preclinical resensitization hypotheses.",
        "confidence": "Medium",
        "confidence_rationale": "Multi-center retrospective real-world cohort (n=94) demonstrating clinical failure of preclinical hypothesis.",
        "is_negative_finding": True,
        "negative_classification": "Failed replication"
    }
]

DEMO_CONTRADICTIONS = [
    {
        "id": "contra-001",
        "evidence_a_id": "ev-001",
        "evidence_b_id": "ev-002",
        "topic": "Drug A Efficacy: Biomarker X+ vs Biomarker X- Populations",
        "summary": "Smith et al. (2024) reported profound progression-free survival benefit with Drug A (18.9 vs 10.2 months, HR 0.46, P<0.001), whereas Johnson et al. (2023) demonstrated null efficacy benefit over chemotherapy (3.4 vs 3.6 months, HR 1.04, P=0.74).",
        "population_diff": "Treatment-naïve advanced cohort vs Unselected pretreated cohort",
        "biomarker_diff": "Biomarker X+ (sensitizing mutation) vs Biomarker X- (wild-type)",
        "dosage_diff": "Identical daily oral dosing (80mg)",
        "endpoint_diff": "Both measured Progression-Free Survival by RECIST 1.1",
        "study_design_diff": "Phase III RCT vs Phase II/III Multicenter Controlled Trial",
        "sample_size_diff": "n=240 vs n=180",
        "possible_explanation": "The primary contributing factor is molecular stratification: Drug A's kinase selectivity requires Biomarker X activation. In Biomarker X-negative tumors, the target is unexpressed, leading to complete absence of therapeutic efficacy.",
        "confidence": "High"
    },
    {
        "id": "contra-002",
        "evidence_a_id": "ev-003",
        "evidence_b_id": "ev-004",
        "topic": "Immune Checkpoint Blockade (Drug B): High vs Low/Negative PD-L1 Expression",
        "summary": "Rodriguez et al. (2023) demonstrated massive survival gains with Drug B monotherapy (OS 26.3 vs 13.4 months, HR 0.62, P=0.0004), while Patel et al. (2024) found no statistically significant benefit when adding Drug B to chemotherapy in PD-L1 negative tumors (OS 14.1 vs 13.0 months, HR 0.89, P=0.38).",
        "population_diff": "First-line metastatic adenocarcinoma/squamous vs Broad mixed histologic types",
        "biomarker_diff": "PD-L1 TPS >= 50% vs PD-L1 TPS < 1%",
        "dosage_diff": "Drug B 200mg monotherapy vs Drug B 200mg + carboplatin/pemetrexed",
        "endpoint_diff": "Both evaluated Overall Survival (OS)",
        "study_design_diff": "Phase III Double-blind RCT vs Phase III Double-blind RCT",
        "sample_size_diff": "n=305 vs n=220",
        "possible_explanation": "Potential contributing factors center on tumor microenvironment immunogenicity: PD-L1 high tumors exhibit pre-existing cytotoxic T-cell infiltration responsive to checkpoint inhibition, whereas PD-L1 negative tumors represent immunologically 'cold' microenvironments.",
        "confidence": "High"
    }
]

DEMO_GAPS = [
    {
        "id": "gap-001",
        "title": "Evidence Vacuum in Biomarker X-Negative & Atypical Co-Mutation Subgroups",
        "description": "While Drug A is extensively characterized in canonical Biomarker X+ cohorts, published literature reveals an acute lack of controlled trials evaluating tailored therapeutic regimens in Biomarker X-negative or atypical compound mutation cohorts.",
        "known_evidence": "Drug A delivers ~18.9 months median PFS in canonical Biomarker X+ NSCLC (Smith et al., 2024). Monotherapy is ineffective in unselected Biomarker X- cohorts (Johnson et al., 2023).",
        "uncertain_evidence": "Whether epigenetic priming or combination bispecific antibodies can re-sensitize Biomarker X- tumors remains completely unresolved across clinical datasets.",
        "missing_evidence": "No prospective randomized trials evaluating targeted combination therapies specifically in Biomarker X- or compound exon 18/20 alteration subsets.",
        "why_it_matters": "Over 50% of advanced NSCLC patients lack canonical Biomarker X activating alterations and have limited durable therapeutic options beyond cytotoxic chemotherapy.",
        "evidence_coverage": 22.0,
        "supporting_studies_count": 5,
        "supporting_studies_summary": [
            {"label": "Johnson et al., 2023", "result": "Null result", "sample_size": "n=180"},
            {"label": "Smith et al., 2024", "result": "Positive", "sample_size": "n=240"},
            {"label": "Weber et al., 2022", "result": "Failed replication", "sample_size": "n=94"}
        ],
        "confidence": "High"
    },
    {
        "id": "gap-002",
        "title": "Uncharacterized Non-Genomic Bypass Resistance in Biomarker Y (KRAS G12C) Inhibition",
        "description": "Initial response rates of 37% to Biomarker Y inhibitors are followed by rapid disease progression within 6-7 months, with over 34% of resistant tumors exhibiting no identifiable genomic driver mutations.",
        "known_evidence": "Biomarker Y inhibitors produce ~6.8 months median PFS (Chen et al., 2024). Secondary RAS/MET mutations explain resistance in 43% of cases (Henderson et al., 2023).",
        "uncertain_evidence": "Mechanisms governing resistance in the remaining 34% without detectable genomic alterations are discordant across small single-institution series.",
        "missing_evidence": "Multi-omic single-cell longitudinal biopsy studies tracing transcriptional and microenvironmental remodeling during on-treatment progression.",
        "why_it_matters": "Identifying actionable non-genomic bypass mechanisms is essential to designing upfront combination regimens that prevent early disease recurrence.",
        "evidence_coverage": 31.0,
        "supporting_studies_count": 4,
        "supporting_studies_summary": [
            {"label": "Chen et al., 2024", "result": "Positive", "sample_size": "n=126"},
            {"label": "Henderson et al., 2023", "result": "Mixed", "sample_size": "n=82"}
        ],
        "confidence": "Medium"
    },
    {
        "id": "gap-003",
        "title": "Safe Optimal Sequencing of Targeted Kinase Inhibitors and Immunotherapy",
        "description": "Concurrent combination of targeted TKIs (Drug A) and anti-PD-1 agents (Drug B) causes fatal pulmonary toxicity (Garcia et al., 2023), yet safe sequential interval strategies remain unstandardized.",
        "known_evidence": "Concurrent administration yields 38% ILD/pneumonitis and is prohibited (Garcia et al., 2023). Sequential mono-agents demonstrate individual efficacy.",
        "uncertain_evidence": "Required washout period between TKI and immune checkpoint inhibitor to avoid severe delayed immune-related adverse events is unknown.",
        "missing_evidence": "Prospective pharmacodynamic sequencing trials assessing immune checkpoint expression kinetics following targeted TKI discontinuation.",
        "why_it_matters": "Clinicians currently lack evidence-based guidance for switching between targeted agents and immunotherapies without risking life-threatening pneumonitis.",
        "evidence_coverage": 18.0,
        "supporting_studies_count": 4,
        "supporting_studies_summary": [
            {"label": "Garcia et al., 2023", "result": "Early termination", "sample_size": "n=48"},
            {"label": "Rodriguez et al., 2023", "result": "Positive", "sample_size": "n=305"}
        ],
        "confidence": "High"
    }
]

DEMO_HYPOTHESES = [
    {
        "id": "hyp-001",
        "research_question": "Does biomarker stratification modify response to Drug A and can targeted co-inhibition overcome de novo resistance in Biomarker X- cohorts?",
        "rationale": "Identified from direct contradiction between Smith et al. (PFS 18.9 mo in Biomarker X+) and Johnson et al. (PFS 3.4 mo in Biomarker X-). Resolving this requires investigating whether co-targeting downstream bypass nodes restores therapeutic vulnerability.",
        "observed_evidence_summary": "Smith et al., 2024 (Positive, n=240) vs Johnson et al., 2023 (Null result, n=180). Divergence directly linked to molecular receptor presence.",
        "gap_addressed": "Addresses Evidence Gap 1: Severe evidence deficit in Biomarker X- and atypical non-canonical mutation populations.",
        "uncertainty_unresolved": "Identifies whether molecular bypass co-inhibition can yield clinical responses in biomarker-negative tumors.",
        "supporting_studies": [
            {"id": "paper-001", "label": "Smith et al., 2024", "result_type": "positive", "confidence": "High"},
            {"id": "paper-002", "label": "Johnson et al., 2023", "result_type": "null", "confidence": "High"},
            {"id": "paper-008", "label": "Weber et al., 2022", "result_type": "negative", "confidence": "Medium"}
        ],
        "novelty_score": 88.0,
        "gap_score": 91.0,
        "feasibility_score": 68.0,
        "impact_score": 79.0,
        "overall_score": 82.0,  # 88*0.3 + 91*0.3 + 68*0.2 + 79*0.2 = 82.2 -> 82
        "tier": "High opportunity",
        "confidence": "High",
        "is_saved": True
    },
    {
        "id": "hyp-002",
        "research_question": "Can concurrent vertical pathway inhibition (SHP2/SOS1 + KRAS G12C) prevent non-genomic adaptive resistance in Biomarker Y-mutant lung adenocarcinoma?",
        "rationale": "Formulated from findings in Chen et al. and Henderson et al. where 34% of resistant tumors showed non-genomic bypass. Upstream vertical pathway inhibition has shown promise in preclinical models to shut down feedback reactivation.",
        "observed_evidence_summary": "Chen et al., 2024 (Positive, ORR 37.1%) and Henderson et al., 2023 (34% non-genomic resistance without targetable mutation).",
        "gap_addressed": "Addresses Evidence Gap 2: Rapid disease progression and unknown non-genomic bypass mechanisms in KRAS G12C NSCLC.",
        "uncertainty_unresolved": "Determines whether upfront vertical blockade delays resistance onset compared to sequential second-line salvage.",
        "supporting_studies": [
            {"id": "paper-005", "label": "Chen et al., 2024", "result_type": "positive", "confidence": "Medium"},
            {"id": "paper-010", "label": "Henderson et al., 2023", "result_type": "mixed", "confidence": "Medium"}
        ],
        "novelty_score": 84.0,
        "gap_score": 86.0,
        "feasibility_score": 74.0,
        "impact_score": 85.0,
        "overall_score": 83.0,  # 84*0.3 + 86*0.3 + 74*0.2 + 85*0.2 = 82.8 -> 83
        "tier": "High opportunity",
        "confidence": "High",
        "is_saved": False
    },
    {
        "id": "hyp-003",
        "research_question": "What is the optimal minimal washout interval between targeted TKI discontinuation and immune checkpoint initiation to prevent life-threatening pulmonary toxicity?",
        "rationale": "Derived from early trial termination in Garcia et al. (38% ILD) contrasted with strong monotherapy efficacy in Rodriguez et al. Defining safe transition timing is an urgent clinical unmet need.",
        "observed_evidence_summary": "Garcia et al., 2023 (Negative/Early Termination due to 38% ILD pneumonitis) vs Rodriguez et al., 2023 (Positive, n=305).",
        "gap_addressed": "Addresses Evidence Gap 3: Total lack of standardized pharmacodynamic sequencing guidelines between kinase inhibitors and immunotherapies.",
        "uncertainty_unresolved": "Establishes biological threshold of immune activation recovery vs residual drug half-life interaction.",
        "supporting_studies": [
            {"id": "paper-006", "label": "Garcia et al., 2023", "result_type": "negative", "confidence": "High"},
            {"id": "paper-003", "label": "Rodriguez et al., 2023", "result_type": "positive", "confidence": "High"}
        ],
        "novelty_score": 76.0,
        "gap_score": 80.0,
        "feasibility_score": 78.0,
        "impact_score": 72.0,
        "overall_score": 77.0,  # 76*0.3 + 80*0.3 + 78*0.2 + 72*0.2 = 76.8 -> 77
        "tier": "Strong",
        "confidence": "Medium",
        "is_saved": False
    }
]
